In [1]:
import numpy as np
import pandas as pd

In [2]:
Data= pd.read_csv('play_data.csv')
Data.head()

day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [3]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
Data['outlook']=le.fit_transform(Data['outlook'])
Data['temp']=le.fit_transform(Data['temp'])
Data['humidity']=le.fit_transform(Data['humidity'])
Data['wind']=le.fit_transform(Data['wind'])
Data['play']=le.fit_transform(Data['play'])

In [4]:
X=Data[['outlook',	'temp',	'humidity',	'wind']].values
y=Data['play'].values

In [13]:
 X
# y

array([[2, 1, 0, 1],
       [2, 1, 0, 0],
       [0, 1, 0, 1],
       [1, 2, 0, 1],
       [1, 0, 1, 1],
       [1, 0, 1, 0],
       [0, 0, 1, 0],
       [2, 2, 0, 1],
       [2, 0, 1, 1],
       [1, 2, 1, 1],
       [2, 2, 1, 0],
       [0, 2, 0, 0],
       [0, 1, 1, 1],
       [1, 2, 0, 0]])

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3)

In [6]:
y_train

array([1, 1, 1, 1, 0, 0, 1, 0, 1])

In [7]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [8]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [9]:
y_pred = model.predict(X_test)
y_pred

array([1, 1, 1, 1, 1])

In [10]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[0, 2],
       [0, 3]])

In [11]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)*100
acc

60.0

In [17]:
y_new=model.predict([[2,0,0,0]])
if y_new == 1:
  print("play Game")
else:
  print ("do not play Game")

play Game
